/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as NetzplanRouteImport } from './routes/netzplan'
import { Route as BaustellenRouteImport } from './routes/baustellen'
import { Route as IndexRouteImport } from './routes/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const NetzplanRoute = NetzplanRouteImport.update({
  id: '/netzplan',
  path: '/netzplan',
  getParentRoute: () => rootRouteImport,
} as any)
const BaustellenRoute = BaustellenRouteImport.update({
  id: '/baustellen',
  path: '/baustellen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baustellen': typeof BaustellenRoute
  '/netzplan': typeof NetzplanRoute
  '/profil': typeof ProfilRoute
  '/timer': typeof TimerRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baustellen': typeof BaustellenRoute
  '/netzplan': typeof NetzplanRoute
  '/profil': typeof ProfilRoute
  '/timer': typeof TimerRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baustellen': typeof BaustellenRoute
  '/netzplan': typeof NetzplanRoute
  '/profil': typeof ProfilRoute
  '/timer': typeof TimerRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/baustellen' | '/netzplan' | '/profil' | '/timer' | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/baustellen' | '/netzplan' | '/profil' | '/timer' | '/voice'
  id:
    | '__root__'
    | '/'
    | '/baustellen'
    | '/netzplan'
    | '/profil'
    | '/timer'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaustellenRoute: typeof BaustellenRoute
  NetzplanRoute: typeof NetzplanRoute
  ProfilRoute: typeof ProfilRoute
  TimerRoute: typeof TimerRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netzplan': {
      id: '/netzplan'
      path: '/netzplan'
      fullPath: '/netzplan'
      preLoaderRoute: typeof NetzplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baustellen': {
      id: '/baustellen'
      path: '/baustellen'
      fullPath: '/baustellen'
      preLoaderRoute: typeof BaustellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaustellenRoute: BaustellenRoute,
  NetzplanRoute: NetzplanRoute,
  ProfilRoute: ProfilRoute,
  TimerRoute: TimerRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
